# Generated by Django 6.0.4 on 2026-04-24 21:22

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_latitude_listing_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'listing_type', 'price'], name='listing_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(django.db.models.functions.text.Upper('city'), name='listing_city_upper_idx'),
        ),
    ]
