# Generated by Django 6.0.4 on 2026-04-24 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_city_alter_listing_listing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['price'], name='listing_price_active_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['rooms', 'price'], name='listing_rooms_price_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(condition=models.Q(('is_active', True), ('latitude__isnull', False), ('longitude__isnull', False)), fields=['latitude', 'longitude'], name='listing_geo_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['owner', '-created_at'], name='listing_owner_date_idx'),
        ),
    ]
