# Generated by Django 6.0.4 on 2026-04-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_listing_price_active_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video_review_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='virtual_tour_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='virtual_tour_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
